CREATE TABLE IF NOT EXISTS USERS (
	ID MEDIUMINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(24) NOT NULL,
	PASSWORD VARBINARY(64) NOT NULL,
	SEX TINYINT NOT NULL,
	AGE TINYINT NOT NULL,
	LAST_CONNECTION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LEVEL MEDIUMINT NOT NULL DEFAULT 1,
	XP MEDIUMINT NOT NULL DEFAULT 0,
	SKIN SMALLINT NOT NULL,
	HUNGER FLOAT NOT NULL DEFAULT 0.0,
	THIRST FLOAT NOT NULL DEFAULT 0.0
);